server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/document-service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      #ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

flyway:
  locations: classpath:db/migration,classpath:db/data
  baseline-on-migrate: true

jackson:
  deserialization:
    fail-on-unknown-properties: false











